### ISSUE TITLE
Possibility of maintaining plugin, or supporting a forked version if maintaining is not an option?

### ISSUE THREAD

**Issue by xCykrix** [hazae41/mc-chestui#2]
I recently was taking a look at developing Spigot plugins with Kotlin and came across this API. I cannot find one of a similar caliber and would love to see this updated or possibly even attempt to do so myself in a fork. I feel it would be a super useful and powerful API to still have.

**Comment by hazae41** [comment]
Yes, feel free to fork it or make pull requests

But I think we also need to update Kotlin libs

I am busy developing [Saurus](https://saurusmc.org), this will allow us to ditch chest UIs completely and use real websites/apps

**Comment by Mhugi-HXYZ** [comment]
I got 1.16 mats to work on https://github.com/Mhugi-HXYZ/mc-chestui
Haven't tested it much and use at your own risk, etc etc

**Comment by hazae41** [comment]
Thanks, I will check this out

**Comment by hazae41** [comment]
Done! I've completely rewritten the plugin
